config/routes.rb
Icms::Application.routes.draw do
  
  
  scope "/my" do
    
    match 'login'              => "guser_sessions#login" ,  :as => :mypage_login, :via => :get
    match 'logout'             => 'guser_sessions#destroy', :as => :mypage_logout, :via => :get
    match 'signup'             => "guser_sessions#signup" , :as => :mypage_signup, :via => :get
    match 'fb_callback_signup' => "guser_sessions#fb_callback_signup" , :as => :fb_callback_signup, :via => :get
    match 'fb_callback_login'  => "guser_sessions#fb_callback_login" ,  :as => :fb_callback_login, :via => :get
    resources :favorites do
     get 'add' , :on => :collection
    end
    resources :my_entries
  end

  scope "/manager" do
    resources :action_logs
    
    resources :app_configs
    
    resources :user_profiles do
      get 'fb_callback_assoc', :on => :collection
      get 'fb_assoc_cancel', :on => :collection
    end
  
    resources :users
  
    resources :libraries
  
    resources :forms do
      get 'download'
    end
  
    resources :fields
  
    resources :entry_metas
  
  
    resource :user_session do
      get 'fb_callback'
    end
    
    
 
    
    match 'entries/import' => 'entries#import', :as => :entries_import, :via => :get
    match 'entries/import' => 'entries#import_post', :as => :entries_import_post, :via => :post
    
    resources :entries
    
    match 'triggers/sweep_cache' => 'welcome#sweep_cache_trigger', :via => :get, :as => :admin_triggers_sweep_cache
    
    match 'logout' => 'user_sessions#destroy', :as => :logout, :via => :get
    
    match 'menu' => 'entries#index', :as => :admin_menu , :via => :get
    match 'forward' => 'user_sessions#forward' , :via => :get
    match 'sweep_cache' => 'welcome#sweep_cache', :as => :admin_sweep_cache , :via => :get
    match 'app_reload' => 'welcome#reload', :as => :admin_app_reload , :via => :get
    match 'geocode_picker' => 'welcome#geocode_picker', :as => :admin_geocode_picker , :via => :get
    match 'contents/:name/:id' => 'contents#show_preview',  :as => :contents_detail_preview , :via => :get
    match 'extra' => "app_configs#extra" , :as => :admin_extra_menu , :via => :get
    match '/' => 'user_sessions#new'  , :via => :get   
  end

  match 'admin/' => 'welcome#manage_legacy' , :via => :get
  match 'admin/*path' => 'welcome#manage_legacy' , :via => :get
  
  
  scope "/api" do
    resources :cms_users
  end

  match 'index' => "contents#top" , :via => :get
  root :to => "contents#top"

  

  
  scope "/javascripts/tiny_mce/plugins/advimage/" do
    match 'image.htm'  => 'rfiles#new',   :as => :rfile_upload , :via => :get
    match ':id.html'   => 'rfiles#show',  :as => :rfile_show, :via => :get
    match ':id.update' => 'rfiles#update',:as => :rfile, :via => :put
    match ':id.update' => 'rfiles#destroy' ,             :via => :delete
    match ':id.edit'   => 'rfiles#edit',  :as => :edit_rfile, :via => :get
     
    resources :rfiles
  end
  
  get 'feedbacks(.:format)' => 'feedbacks#index'
  post 'feedbacks(.:format)' => 'feedbacks#send_message'
  get 'feedbacks_search' => 'feedbacks#search'  
  
  get 'c_ir/library' => 'ir#library'
  get 'c_ir/library/:year' => 'ir#past_library'
  
  get 'c_ir/contact' =>  'ir#contact'
  post 'c_ir/contact' => 'ir#send_message'  
  

  match 'contents/:name/archives/:date_field_name/:year-:month'     => 'contents#monthly_archives', :as => :contents_monthly_archives , :via => :get
  match 'contents/:name/index-print'     => 'contents#index_print', :as => :contents_page_print , :via => :get
  
  match 'contents/:name/index-:page'     => 'contents#index', :as => :contents_page , :via => :get
  match 'contents/:name/index'     => 'contents#index', :as => :contents_index, :via => :get
  match 'contents/:name/:id' => 'contents#show',  :as => :contents_detail, :via => :get
  match 'contents/:name/' => 'contents#spelling' , :via => :get
  
  match '*other'     => 'contents#static', :as => :contents_static , :via => :get

end

app/controllers/my_entries_controller.rb
#coding:utf-8
class MyEntriesController < ApplicationController
  layout "mypage"
  
  #cache_sweeper :contents_cache_sweeper
  #↓表のページのentries_for_monthly_archivesを使うため、必要
  include ContentsRenderer
  
  helper_method :entries_for_monthly_archives  , :headline, :cf_filter

  before_filter :my_entires_filter
  private 
  def my_entires_filter
    @entry_picker_path = File.join(root_path, "entry_picker2")
  end
  public
  
  def new
    
    
    @entry = Entry.new
    @entry.form_id = Form.where(:template_name => AppConfig.get("fb_user_permitted_form_name")).first.id #current_user.permitted_forms.first.id
    render :action => :edit
  end
  
  def edit
    @entry = Entry.find(params[:id])
    if @entry.user_has_kousin_kengen?(current_user)
      @entry.preload_custom_fields
      render_custom_template @entry.form_id, "edit"
    else
      flash[:error] = "権限がありません"
      redirect_to favorites_path
    end
  end
  
  
  # 
  #クリエイト
  #
  def create
    
    @entry = Entry.new(params[:entry])
    
    @entry.updated_by = @entry.created_by = current_user
    #button_action_name = get_submit_action
    #最初から公開状態にする
    errors = [] # Entry.update_status(@entry,  button_action_name, current_user )
    @entry.status = 'publish'
    respond_to do |format|
      Entry.transaction do
        
        begin
          if errors.empty? && @entry.save && @entry.save_entry_metas(params)
            @entry.after_all_save
            format.html {
              flash.now[:notice] = '保存されました。'
              
              #render_custom_template( @entry.form_id, "edit")
              redirect_to favorites_path
            }
            
          else
            logger.debug "エラーが発生しました"              
            raise ActiveRecord::RecordInvalid, @entry       
            
            
            
          end
        rescue ActiveRecord::RecordInvalid => e
          format.html {
            flash.now[:error] = "エラー#{errors.join('')}"
            render_custom_template( @entry.form_id, "edit") 
          }
          raise ActiveRecord::Rollback
        end
        
      end
    end
  end
  
  # 
  #アップデート 
  #
  def update
    
    @entry = Entry.find(params[:id])
    unless @entry.user_has_kousin_kengen?(current_user)
      flash[:error] = "権限がありません"
      return redirect_to favorites_path      
    end
    
    @entry.updated_by =  current_user
    #submit_action = get_submit_action

    
    errors = [] #Entry.update_status(@entry, submit_action , current_user )
    respond_to do |format|
      
      Entry.transaction do
        
        begin
          if errors.empty? && @entry.update_attributes(params[:entry]) && @entry.save_entry_metas(params)
            @entry.after_all_save
            format.html { 
              flash.now[:notice] = '保存されました。'
              #render_custom_template( @entry.form_id, "edit")
              redirect_to favorites_path
            }
            
            
          else
            logger.debug "エラーが発生しました"              
            raise ActiveRecord::RecordInvalid, @entry
            
          end
        rescue ActiveRecord::RecordInvalid => e
          format.html {
            flash.now[:error] = "エラー#{errors.join('')}"
            render_custom_template( @entry.form_id, "edit") 
            
          }
          raise ActiveRecord::Rollback
        end
      end
    end
  end  
  
  
  def destroy
    @entry = Entry.find(params[:id])
    unless @entry.user_has_kousin_kengen?(current_user)
      flash[:error] = "権限がありません"
      return redirect_to favorites_path      
    end
    @entry.destroy
     redirect_to favorites_path, :notice => "削除されました。"
  end
  
  #
  #カスタムテンプレート描画
  #
  def render_custom_template(form_id, file_name)
    render :action => file_name
  end  
  
  #
  #submitアクション名
  #
  def get_submit_action
    params[:submit_action].blank? ?  "fumeina_action" : params[:submit_action].keys.first
  end  
  
  
  #
  #ログインしていないとき、ログインを促す画面に遷移する。そのリダイレクト先URLを返す
  #オーバーライド用
  def url_for_login_required
    #"http://www.izumo.ne.jp/"
    #fb_login_url
    mypage_login_path
  end    
end

app/views/my_entries/_footer.html.erb
</div>
</div>
</div>
</body>
</html>

app/views/my_entries/_form.html.erb
<%= form_for(@entry, :url => (@entry.new_record? ? my_entries_path : my_entry_path(@entry.id) ) ,  :html => {:multipart => true, :class => "form"}) do |f| %>
  <%= f.hidden_field :form_id %>
  
  <%#↓エラーメッセージ %>
  <%=render :file => "_share/validation_message", :locals => {:record => @entry } %>
  
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title, :class => "text_field" %>
  </div>
  
  <%if @entry.form.use_content_field %>
  <div class="field">
    <%= f.label :content, "内容" %><br />
    <%= f.text_area :content, :rows=>"15", :cols=>"80", :class => "wysiwyg" %>
  </div>
  <%end%>
  
 


  
  <!--カスタムフィールド-->
  <table id="customfield">
 
  <% @entry.form.fields.each do |field|  %>
  <tr>
    <th class="cf_container"> <%=field.label %>: </th>
    <td class="cf_container">
    <%=cf_tag field.name, @entry %>
	 
	 &nbsp;
	 <% if field.required? %>
	   ※必須
	 <%end%>
	 &nbsp;
	 
	 <%=field.description %>
	 <%#=field.name %> 
	 <%#=field.ftype %>
    </td>
  </tr>
  <%end #fields.each %>
  
  </table>  
  
  
  <div class="field" id="date">

    <%= f.hidden_field :date_begin %>

  </div>
  

  <div class="actions" id="button" >

	
	
  	  <%= f.submit "保存する", :class => "button", :name=>"submit_action[kettei]", :disable_with => '登録中...' %>
	
	

  </div>
  
  
  <%unless @entry.new_record? %>
	  <div class="field" style="display:none">
	    作成日<br />
	    <%= @entry.created_at.strftime("%Y年%m月%d日 %H:%M") %>
		
	  </div>
	  <div class="field" style="display:none">
	    更新日<br />
	    <%= @entry.updated_at.strftime("%Y年%m月%d日 %H:%M") %>
	  </div>    
  <%end%>
    
<% end %>

app/views/my_entries/_header.html.erb
<!DOCTYPE html>
<html>
<head>

  
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/warehouse/style", "web-app-theme/override", :cache => false %>


	<script type="text/javascript" src="http://www.google.com/jsapi"></script>
	<script type="text/javascript" >google.load("jquery", "1.6.2");</script>


  <%= javascript_include_tag "rails", :cache => false %>
  <%= javascript_include_tag "application", :cache => false %>
  
  <%= csrf_meta_tag %>

  <%#<title>タグ,ページ固有のCSS/Javascript等のhead要素は下記インクルード内で指定 
  %>  
  <%= yield :head %>
  
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><%=link_to "マイページ" , favorites_path %></h1>
      <div id="user-navigation">
        <ul class="wat-cf">

        </ul>
      </div>
	  
      <div id="main-navigation">

        <ul class="wat-cf">
        </ul>
      </div>
	  
    </div>    
	
	<%#通知メッセージ、エラーメッセージ%>
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
	  <div id="main">

app/views/my_entries/edit.html.erb
<% content_for :head do %>
<%= javascript_include_tag "tiny_mce/tiny_mce.js" %>
<%= javascript_include_tag "admin_tiny_mce_init.js" %>
<script type="text/javascript">
	//tinymce_initに渡す
	var _admin_tiny_mce_content_css =  "<%=stylesheet_path('wysiwyg_content.css')%>";
	admin_tiny_mce_init(_admin_tiny_mce_content_css);
</script>

<!--カレンダー-->
<%= stylesheet_link_tag "jquery.datepick.css"%>
<%= javascript_include_tag "jquery.datepick.js" %>
<%= javascript_include_tag "jquery.datepick-ja.js" %>
<!--app-->
<%= javascript_include_tag "rails", :cache => false %>
<%= javascript_include_tag "application", :cache => false %>




	
<title><%= @entry.new_record? ? "ページの新規作成" : "ページの編集 : #{@entry.title}" %></title>
<% end # content_for :head %>

<% 
@page_title = "Myページ";
@page_id = "mypage";
@category = "mypage" 
@body_class = "edit"
%> 

   
      <%=render 'contents/sub_header' %><img src="/common/images/title/title_mypage.png">
<div id="right_inner">
<h3><%= @entry.new_record? ? "新しいmyたびの作成" : "ページの編集 : #{@entry.title}" %></h3>

        <div class="block" id="block-forms">
          <div class="secondary-navigation">
            <ul class="wat-cf clearfix" style="border:1px solid red;display:none;">

<%#通知メッセージ、エラーメッセージ%>
<% flash.each do |type, message| -%>
  <div class="message <%= type %>">
      <p><%= message %></p>
   </div>
<% end -%>

              <li class="first"><%=link_to "戻る", favorites_path %></li>
              

            </ul>
          </div>
          <div class="content">

            <div class="inner">

<%= render 'form' %>
            </div>
		  </div>
		</div>
	  


</div>
<%=render 'contents/sub_footer' %>