config/routes.rb
Icms::Application.routes.draw do
  
  
  scope "/my" do
    
    match 'login'              => "guser_sessions#login" ,  :as => :mypage_login, :via => :get
    match 'logout'             => 'guser_sessions#destroy', :as => :mypage_logout, :via => :get
    match 'signup'             => "guser_sessions#signup" , :as => :mypage_signup, :via => :get
    match 'fb_callback_signup' => "guser_sessions#fb_callback_signup" , :as => :fb_callback_signup, :via => :get
    match 'fb_callback_login'  => "guser_sessions#fb_callback_login" ,  :as => :fb_callback_login, :via => :get
    resources :favorites do
     get 'add' , :on => :collection
    end
    resources :my_entries
  end

  scope "/manager" do
    resources :action_logs
    
    resources :app_configs
    
    resources :user_profiles do
      get 'fb_callback_assoc', :on => :collection
      get 'fb_assoc_cancel', :on => :collection
    end
  
    resources :users
  
    resources :libraries
  
    resources :forms do
      get 'download'
    end
  
    resources :fields
  
    resources :entry_metas
  
  
    resource :user_session do
      get 'fb_callback'
    end
    
    
 
    
    match 'entries/import' => 'entries#import', :as => :entries_import, :via => :get
    match 'entries/import' => 'entries#import_post', :as => :entries_import_post, :via => :post
    
    resources :entries
    
    match 'triggers/sweep_cache' => 'welcome#sweep_cache_trigger', :via => :get, :as => :admin_triggers_sweep_cache
    
    match 'logout' => 'user_sessions#destroy', :as => :logout, :via => :get
    
    match 'menu' => 'entries#index', :as => :admin_menu , :via => :get
    match 'forward' => 'user_sessions#forward' , :via => :get
    match 'sweep_cache' => 'welcome#sweep_cache', :as => :admin_sweep_cache , :via => :get
    match 'app_reload' => 'welcome#reload', :as => :admin_app_reload , :via => :get
    match 'geocode_picker' => 'welcome#geocode_picker', :as => :admin_geocode_picker , :via => :get
    match 'contents/:name/:id' => 'contents#show_preview',  :as => :contents_detail_preview , :via => :get
    match 'extra' => "app_configs#extra" , :as => :admin_extra_menu , :via => :get
    match '/' => 'user_sessions#new'  , :via => :get   
  end

  match 'admin/' => 'welcome#manage_legacy' , :via => :get
  match 'admin/*path' => 'welcome#manage_legacy' , :via => :get
  
  
  scope "/api" do
    resources :cms_users
  end

  match 'index' => "contents#top" , :via => :get
  root :to => "contents#top"

  

  
  scope "/javascripts/tiny_mce/plugins/advimage/" do
    match 'image.htm'  => 'rfiles#new',   :as => :rfile_upload , :via => :get
    match ':id.html'   => 'rfiles#show',  :as => :rfile_show, :via => :get
    match ':id.update' => 'rfiles#update',:as => :rfile, :via => :put
    match ':id.update' => 'rfiles#destroy' ,             :via => :delete
    match ':id.edit'   => 'rfiles#edit',  :as => :edit_rfile, :via => :get
     
    resources :rfiles
  end
  
  get 'feedbacks(.:format)' => 'feedbacks#index'
  post 'feedbacks(.:format)' => 'feedbacks#send_message'
  get 'feedbacks_search' => 'feedbacks#search'  
  
  get 'c_ir/library' => 'ir#library'
  get 'c_ir/library/:year' => 'ir#past_library'
  
  get 'c_ir/contact' =>  'ir#contact'
  post 'c_ir/contact' => 'ir#send_message'  
  

  match 'contents/:name/archives/:date_field_name/:year-:month'     => 'contents#monthly_archives', :as => :contents_monthly_archives , :via => :get
  match 'contents/:name/index-print'     => 'contents#index_print', :as => :contents_page_print , :via => :get
  
  match 'contents/:name/index-:page'     => 'contents#index', :as => :contents_page , :via => :get
  match 'contents/:name/index'     => 'contents#index', :as => :contents_index, :via => :get
  match 'contents/:name/:id' => 'contents#show',  :as => :contents_detail, :via => :get
  match 'contents/:name/' => 'contents#spelling' , :via => :get
  
  match '*other'     => 'contents#static', :as => :contents_static , :via => :get

end

app/models/entry_meta.rb
#coding:utf-8
class EntryMeta < ActiveRecord::Base
  belongs_to :field
  mount_uploader :file_value, GeneralUploader
end

app/controllers/entry_metas_controller.rb
#coding:utf-8
class EntryMetasController < ApplicationController
  # GET /entry_metas
  # GET /entry_metas.xml
  def index
    @entry_metas = EntryMeta.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @entry_metas }
    end
  end

  # GET /entry_metas/1
  # GET /entry_metas/1.xml
  def show
    @entry_meta = EntryMeta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @entry_meta }
    end
  end

  # GET /entry_metas/new
  # GET /entry_metas/new.xml
  def new
    @entry_meta = EntryMeta.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @entry_meta }
    end
  end

  # GET /entry_metas/1/edit
  def edit
    @entry_meta = EntryMeta.find(params[:id])
  end

  # POST /entry_metas
  # POST /entry_metas.xml
  def create
    @entry_meta = EntryMeta.new(params[:entry_meta])

    respond_to do |format|
      if @entry_meta.save
        format.html { redirect_to(@entry_meta, :notice => 'Entry meta was successfully created.') }
        format.xml  { render :xml => @entry_meta, :status => :created, :location => @entry_meta }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @entry_meta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /entry_metas/1
  # PUT /entry_metas/1.xml
  def update
    @entry_meta = EntryMeta.find(params[:id])

    respond_to do |format|
      if @entry_meta.update_attributes(params[:entry_meta])
        format.html { redirect_to(@entry_meta, :notice => 'Entry meta was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @entry_meta.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /entry_metas/1
  # DELETE /entry_metas/1.xml
  def destroy
    @entry_meta = EntryMeta.find(params[:id])
    @entry_meta.destroy

    respond_to do |format|
      format.html { redirect_to(entry_metas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/entry_metas_helper.rb
module EntryMetasHelper
end

app/views/entry_metas/_form.html.erb
<%= form_for(@entry_meta) do |f| %>
  <% if @entry_meta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry_meta.errors.count, "error") %> prohibited this entry_meta from being saved:</h2>

      <ul>
      <% @entry_meta.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :entry_id %><br />
    <%= f.text_field :entry_id %>
  </div>
  <div class="field">
    <%= f.label :field_id %><br />
    <%= f.text_field :field_id %>
  </div>
  <div class="field">
    <%= f.label :string_value %><br />
    <%= f.text_field :string_value %>
  </div>
  <div class="field">
    <%= f.label :text_value %><br />
    <%= f.text_area :text_value %>
  </div>
  <div class="field">
    <%= f.label :int_value %><br />
    <%= f.text_field :int_value %>
  </div>
  <div class="field">
    <%= f.label :date_value %><br />
    <%= f.date_select :date_value %>
  </div>
  <div class="field">
    <%= f.label :float_value %><br />
    <%= f.text_field :float_value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entry_metas/edit.html.erb
<h1>Editing entry_meta</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry_meta %> |
<%= link_to 'Back', entry_metas_path %>

app/views/entry_metas/index.html.erb
<h1>Listing entry_metas</h1>

<table>
  <tr>
    <th>Entry</th>
    <th>Field</th>
    <th>String value</th>
    <th>Text value</th>
    <th>Int value</th>
    <th>Date value</th>
    <th>Float value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @entry_metas.each do |entry_meta| %>
  <tr>
    <td><%= entry_meta.entry_id %></td>
    <td><%= entry_meta.field_id %></td>
    <td><%= entry_meta.string_value %></td>
    <td><%= entry_meta.text_value %></td>
    <td><%= entry_meta.int_value %></td>
    <td><%= entry_meta.date_value %></td>
    <td><%= entry_meta.float_value %></td>
    <td><%= link_to 'Show', entry_meta %></td>
    <td><%= link_to 'Edit', edit_entry_meta_path(entry_meta) %></td>
    <td><%= link_to 'Destroy', entry_meta, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Entry meta', new_entry_meta_path %>

app/views/entry_metas/new.html.erb
<h1>New entry_meta</h1>

<%= render 'form' %>

<%= link_to 'Back', entry_metas_path %>

app/views/entry_metas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Entry:</b>
  <%= @entry_meta.entry_id %>
</p>

<p>
  <b>Field:</b>
  <%= @entry_meta.field_id %>
</p>

<p>
  <b>String value:</b>
  <%= @entry_meta.string_value %>
</p>

<p>
  <b>Text value:</b>
  <%= @entry_meta.text_value %>
</p>

<p>
  <b>Int value:</b>
  <%= @entry_meta.int_value %>
</p>

<p>
  <b>Date value:</b>
  <%= @entry_meta.date_value %>
</p>

<p>
  <b>Float value:</b>
  <%= @entry_meta.float_value %>
</p>


<%= link_to 'Edit', edit_entry_meta_path(@entry_meta) %> |
<%= link_to 'Back', entry_metas_path %>