config/routes.rb
Icms::Application.routes.draw do
  
  
  scope "/my" do
    
    match 'login'              => "guser_sessions#login" ,  :as => :mypage_login, :via => :get
    match 'logout'             => 'guser_sessions#destroy', :as => :mypage_logout, :via => :get
    match 'signup'             => "guser_sessions#signup" , :as => :mypage_signup, :via => :get
    match 'fb_callback_signup' => "guser_sessions#fb_callback_signup" , :as => :fb_callback_signup, :via => :get
    match 'fb_callback_login'  => "guser_sessions#fb_callback_login" ,  :as => :fb_callback_login, :via => :get
    resources :favorites do
     get 'add' , :on => :collection
    end
    resources :my_entries
  end

  scope "/manager" do
    resources :action_logs
    
    resources :app_configs
    
    resources :user_profiles do
      get 'fb_callback_assoc', :on => :collection
      get 'fb_assoc_cancel', :on => :collection
    end
  
    resources :users
  
    resources :libraries
  
    resources :forms do
      get 'download'
    end
  
    resources :fields
  
    resources :entry_metas
  
  
    resource :user_session do
      get 'fb_callback'
    end
    
    
 
    
    match 'entries/import' => 'entries#import', :as => :entries_import, :via => :get
    match 'entries/import' => 'entries#import_post', :as => :entries_import_post, :via => :post
    
    resources :entries
    
    match 'triggers/sweep_cache' => 'welcome#sweep_cache_trigger', :via => :get, :as => :admin_triggers_sweep_cache
    
    match 'logout' => 'user_sessions#destroy', :as => :logout, :via => :get
    
    match 'menu' => 'entries#index', :as => :admin_menu , :via => :get
    match 'forward' => 'user_sessions#forward' , :via => :get
    match 'sweep_cache' => 'welcome#sweep_cache', :as => :admin_sweep_cache , :via => :get
    match 'app_reload' => 'welcome#reload', :as => :admin_app_reload , :via => :get
    match 'geocode_picker' => 'welcome#geocode_picker', :as => :admin_geocode_picker , :via => :get
    match 'contents/:name/:id' => 'contents#show_preview',  :as => :contents_detail_preview , :via => :get
    match 'extra' => "app_configs#extra" , :as => :admin_extra_menu , :via => :get
    match '/' => 'user_sessions#new'  , :via => :get   
  end

  match 'admin/' => 'welcome#manage_legacy' , :via => :get
  match 'admin/*path' => 'welcome#manage_legacy' , :via => :get
  
  
  scope "/api" do
    resources :cms_users
  end

  match 'index' => "contents#top" , :via => :get
  root :to => "contents#top"

  

  
  scope "/javascripts/tiny_mce/plugins/advimage/" do
    match 'image.htm'  => 'rfiles#new',   :as => :rfile_upload , :via => :get
    match ':id.html'   => 'rfiles#show',  :as => :rfile_show, :via => :get
    match ':id.update' => 'rfiles#update',:as => :rfile, :via => :put
    match ':id.update' => 'rfiles#destroy' ,             :via => :delete
    match ':id.edit'   => 'rfiles#edit',  :as => :edit_rfile, :via => :get
     
    resources :rfiles
  end
  
  get 'feedbacks(.:format)' => 'feedbacks#index'
  post 'feedbacks(.:format)' => 'feedbacks#send_message'
  get 'feedbacks_search' => 'feedbacks#search'  
  
  get 'c_ir/library' => 'ir#library'
  get 'c_ir/library/:year' => 'ir#past_library'
  
  get 'c_ir/contact' =>  'ir#contact'
  post 'c_ir/contact' => 'ir#send_message'  
  

  match 'contents/:name/archives/:date_field_name/:year-:month'     => 'contents#monthly_archives', :as => :contents_monthly_archives , :via => :get
  match 'contents/:name/index-print'     => 'contents#index_print', :as => :contents_page_print , :via => :get
  
  match 'contents/:name/index-:page'     => 'contents#index', :as => :contents_page , :via => :get
  match 'contents/:name/index'     => 'contents#index', :as => :contents_index, :via => :get
  match 'contents/:name/:id' => 'contents#show',  :as => :contents_detail, :via => :get
  match 'contents/:name/' => 'contents#spelling' , :via => :get
  
  match '*other'     => 'contents#static', :as => :contents_static , :via => :get

end

app/models/field.rb
#coding:utf-8
class Field < ActiveRecord::Base
  has_many :entry_metas, 
    :dependent => :destroy #紐付けされた値も削除  
  
  validates_presence_of :name, :label
  validates_uniqueness_of :name, :scope => [:form_id]
  validates_format_of :name, :with => /\A[a-zA-Z_][a-zA-Z0-9_]*\z/ , :message => ":使用できる文字は半角英数字、アンダーバーです。数字から始まってはいけません。"
  
  after_validation :custom_validation
  #before_upadate :check_sortkey
  
  def required?
    required == 1
  end
  
  def custom_validation
    if errors.empty?
      if Object.new.respond_to? name.to_sym
        errors.add :name, "#{name}は予約されており利用できません。"
      end
      
    end
    

  end

  #フィールドタイプとDB上のフィールド(型)の対応
  def meta_field_name
      meta_field = case self.ftype
        when "image", "file"
        ret = "file_value"
        when "datetime","date"
        ret = "date_value"
        when "textarea","richtext"
        
        ret = "text_value"
        
      else
        
        ret = "string_value"
    end
    return meta_field
  end

  #ラベルと値は
  #値, ラベルのように区切る
  #カンマが無いときは値＝ラベルとみなす
  def options_for_select
    if options2.blank?
      options.split(/[\r\n]+/).map{ |ele|
        arr = ele.to_s.split(",")
        value = arr[0]
        label = arr.size <= 1 ? value : arr[1]
        [label,value] 
        
      }
    else
      table_name, value_field, label_field, order, where = options2.split(',')
      
      table_name.gsub!(/[{}]/, '')
      value_field.gsub!(/[{}]/, '')
      label_field.gsub!(/[{}]/, '')
      
      frm = Form.where("template_name=?", table_name).first
      return [] if frm.blank?
      
      entries = Entry.where("form_id=?", frm.id)
      options = {}
      unless order.blank?
        options[:order] = order
      end
      
      unless where.blank?
        options[:where] = where
      end
      
      unless options.blank?
        entries = Entry.cf_filter(entries, table_name, options )
      end
      
      ret = []
      entries.each {|entry|
        value = entry._cf(value_field)
        label = entry._cf(label_field)
        ret << [label, value]
      }
      
      ret
    end
  end


  
  FIELDTYPE_MAP = {
    "text"=>"テキスト", 
    "textarea"=>"テキスト複数行",
    "richtext"=>"リッチテキスト", 
    "checkbox"=>"チェックボックス", 
    "url"=>"URL", 
    "datetime"=>"日付と時刻",
    "date"=>"日付", 
    "select"=>"ドロップダウン", 
    "radio"=>"ラジオボタン", 
    #"item"=>"アイテム", 
    "image"=>"画像",
    "file" => "ファイル",
    "geocode" => "緯度経度",
    "entry" => "記事参照",
  }.freeze
    
    
  FIELDTYPE_OPTIONS = lambda{
    arr = []
    FIELDTYPE_MAP.each{|k,v|
      arr << [v,k]
    }
    arr
  }.call.freeze  
end

app/controllers/fields_controller.rb
#coding:utf-8
class FieldsController < ApplicationController
  # GET /fields
  # GET /fields.xml
  def index
    @fields = Field.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fields }
    end
  end

  # GET /fields/1
  # GET /fields/1.xml
  def show
    @field = Field.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @field }
    end
  end

  # GET /fields/new
  # GET /fields/new.xml
  def new
    @field = Field.new
    @field.form_id = params[:form_id]
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @field }
    end
  end

  # GET /fields/1/edit
  def edit
    @field = Field.find(params[:id])
  end

  # POST /fields
  # POST /fields.xml
  def create
    @field = Field.new(params[:field])

    respond_to do |format|
      if @field.save
        @field.sortkey = @field.id
        @field.save!
        
        format.html { redirect_to(edit_form_path(@field.form_id), :notice => 'フィールドが追加されました') }
        format.xml  { render :xml => @field, :status => :created, :location => @field }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @field.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fields/1
  # PUT /fields/1.xml
  def update
    @field = Field.find(params[:id])
    Field.transaction do
      respond_to do |format|
        if params[:update_order]
          update_order(params[:update_order],params[:form_id])
          
        end
        
        
        if @field.update_attributes(params[:field])
          format.html { redirect_to(edit_form_path(@field.form_id), :notice => 'フィールドが更新されました。') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @field.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.xml
  def destroy
    @field = Field.find(params[:id])
    @field.destroy

    respond_to do |format|
      format.html { redirect_to(edit_form_path(@field.form_id)) }
      format.xml  { head :ok }
    end
  end
  
  
  private
  def update_order(up_down, form_id)
    form = Form.find(form_id)
    idx = form.fields.index(@field)
    to_idx = nil
    case up_down
      when "up"
        to_idx = idx - 1
    when "down"
      to_idx = idx + 1
    end
    
    if to_idx < 0 || to_idx > form.fields.size - 1
      return
    end
    arr = form.fields
    field_to_move = arr[to_idx]
    arr[to_idx] =  @field
    arr[idx] = field_to_move
    arr.each_with_index do |field,i|
      field.sortkey = "#{i+1}"
      field.save!
    end
  end
  
end

app/helpers/fields_helper.rb
#coding:utf-8
module FieldsHelper
  def ftype_options
    Field::FIELDTYPE_OPTIONS
  end
  
  def ftype_label(name)
    Field::FIELDTYPE_MAP[name]
  end
end

app/views/fields/_form.html.erb
<%= form_for(@field) do |f| %>
<%= f.hidden_field :form_id %>

  <%#↓エラーメッセージ %>
  <%=render :file => "_share/validation_message", :locals => {:record => @field } %>

  <div class="field">
    <%= f.label :name, "ID" %><br />
    <%= f.text_field :name %>※半角英数のみ
  </div>
  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 5 %>
  </div>
  <div class="field">
    <%= f.label :required %><br />
    <%= f.select :required, [["任意",0],["必須",1]] %>
  </div>
  <div class="field">
    <%= f.label :default %><br />
    <%= f.text_field :default %>
  </div>
  <div class="field">
    <%= f.label :ftype %><br />
    <%= f.select :ftype, ftype_options %>
  </div>
  <div class="field">
    <%= f.label :options %><br />※改行で区切って入力してください。<br />
	各要素は値, ラベルのようにカンマで区切る<br />
    <%= f.text_area :options, :rows => 5 %>
  </div>
  
  <div class="field">
    <%= f.label :options2 %><br />
	
    <%= f.text_field :options2 %>
	</div>
  
  <div class="field">
    <%= f.label :sortkey %><br />
    <%= f.text_field :sortkey %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<% content_for :head do %>
  <title>フィールドの編集</title>
 
<% end #content_for :head %>




        <div class="block" id="block-forms-2">
          <div class="secondary-navigation">
          </div>
          <div class="content">
            <h2 class="title">フィールドの編集</h2>
            <div class="inner">
<%= render 'form' %>


<%= link_to '戻る', edit_form_path(@field.form_id) %>

</div>
</div>
</div>

app/views/fields/index.html.erb
<h1>Listing fields</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Label</th>
    <th>Description</th>
    <th>Form</th>
    <th>Required</th>
    <th>Default</th>
    <th>Ftype</th>
    <th>Options</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fields.each do |field| %>
  <tr>
    <td><%= field.name %></td>
    <td><%= field.label %></td>
    <td><%= field.description %></td>
    <td><%= field.form_id %></td>
    <td><%= field.required %></td>
    <td><%= field.default %></td>
    <td><%= ftype_label(field.ftype) %></td>
    <td><%= field.options %></td>
    <td><%= link_to 'Show', field %></td>
    <td><%= link_to 'Edit', edit_field_path(field) %></td>
    <td><%= link_to 'Destroy', field, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Field', new_field_path %>

app/views/fields/new.html.erb
<% content_for :head do %>
  <title>フィールドの作成</title>
 
<% end #content_for :head %>

        <div class="block" id="block-forms-2">
          <div class="secondary-navigation">
          </div>
          <div class="content">
            <h2 class="title">フィールドの作成</h2>
            <div class="inner">

<%= render 'form' %>

<%= link_to '戻る', edit_form_path(@field.form_id) %>

</div>
</div>
</div>

app/views/fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @field.name %>
</p>

<p>
  <b>Label:</b>
  <%= @field.label %>
</p>

<p>
  <b>Description:</b>
  <%= @field.description %>
</p>

<p>
  <b>Form:</b>
  <%= @field.form_id %>
</p>

<p>
  <b>Required:</b>
  <%= @field.required %>
</p>

<p>
  <b>Default:</b>
  <%= @field.default %>
</p>

<p>
  <b>Ftype:</b>
  <%= @field.ftype %>
</p>

<p>
  <b>Options:</b>
  <%= @field.options %>
</p>


<%= link_to 'Edit', edit_field_path(@field) %> |
<%= link_to 'Back', fields_path %>